version: "3.7"

networks:
  traefik_homenet:
    external:
      name: traefik_homenet

volumes:
  shared_data:
    external:
      name: shared_data

services:
  phaneetkssr:
    build:
      context: .
      dockerfile: ./dockerfiles/node_runtime/DockerFile
    container_name: "phaneetkssr"
    volumes:
      - shared_data:/shared
    ports:
      - "3000:3000"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_homenet
    labels:
      - "traefik.enable=true"
      - "traefik.backend=phaneetkssr"
      - "traefik.frontend.rule=Host:phaneetkssr.${DOMAINNAME}"
      - "traefik.port=5601"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_homenet"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
